version: '3'
services:
  graphql:
    build:
      context: .
      dockerfile: .docker/gql/Dockerfile
    command: sh -c "echo 'Starting GQL Server...' && ./starwars.gql-server.linux"
    ports:
      - "8080:8080"
    hostname: gql.dev.intranet
    volumes:
      - ./bin:/app
  angular:
    build:
      context: .
      dockerfile: .docker/ng/Dockerfile
    command: npx ng serve --host 0.0.0.0
    expose:
      - "4200"
    environment:
     - HOST=0.0.0.0
    ports:
      - "4201:4200"
      - "49153:49153"
    volumes:
      - ./app:/usr/src/app
