#! /bin/bash

# this solution only works on linux, but I will keep just for the future!
# https://stackoverflow.com/questions/37242217/access-docker-container-from-host-using-containers-name
docker-compose up & docker run --hostname dns.mageddo --name dns-proxy-server -p 5380:5380 \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /etc/resolv.conf:/etc/resolv.conf \
defreitas/dns-proxy-server